public class BrinCodant {

    public static void main(String[] args) {

        String test = "AGGACAAAGTTTGCCTTACCATATGTTTCCTGATCGTGCGAAAGCCCTTTTCTAGGGACTTGGAGAACACAAGTATTATGAAAAGTACTGATGAAAGTTATTAACAGGTTTCGAAAAATAACTTTACTATCTGACGTGTTGCTTCTGCCGAGGATGACCGTTATTCCTGTTTTTGCATGTATATTTCACGTATGGTTAAATGTGCCAGCGTTGTGGTTTAAAACTAATAGTAATAATATGCTTCTTTGTTCAGTTGGCTAGAGATTTACTACATCCGTCCTTGGAAGAGGAAAAGAAAAAACATAAAAAGAAACGCCTAGTACAAAGTCCAAATTCTTACTTTATGGATGTAAAATGTCCAGGTAAAATTTGAAATCTTAATTCCTTTACTAAAGAAAATTTCTGTAGGGATTGCTAGTGTGGTGTGTATAGTTAAGATACATTAGAACCCTCTGTTGAGTAGAAGTGGGATTACAGAATTGGAAATGTCAGGGACATTTTCATAATAAATGTACTGAAACCATTGTAGAAACATTTCGGGGTAAGTGAAAACAGGCATTCAAAGGAGATATGCCATTTGACTGCACTTGTGGATAATCAAAATGTGGATACTCAAAATAGAGATGTTCTTTAATTGTAAAATACTCACTGGATTTTGACGATGTAGCACAGAAAAAAAATACATTGATTACACTGTTTTTAAAAAATTTTGTGTCGCTGCTAGAAAAGTTTATGTTACACATGTGGCTTGCTGTTTCATAGCACTGAAGTTACTGATTTTTTTACATATTACCAGAAATGTCGAACAGGTGCTGTTTTCCTCTGCTTTTCATTTTTAACATTGCCTTTTTTTTTTTTTAGTTTGCTACAAGATCACCACGGTTTTCAGCCATGCTCAGACAGTGGTTCTTTGTGTAGGTTGTTCAACAGTGTTGTGCCAGCCTACAGGAGGAAAGGCCAGACTCACAGAAGGATTATCATTTGGCATTCTCCAACCCAGTGATGAGATTGATGATTATAAATGTCTCTATCTTCACTGAAAAGTTTAAAGAAATCTTAATGATTACCAAAATAACTTATCTCTCACTGGAAGAGTTCAAGTGGATTGGCAGCAAATCTGAGATCTATTTGGTGTGACCTGGTGAGATCTAAATATGGAGTCAGCACATGATTTTTTTAAGAGTAATATTGCTAAGTAATATTGCTAAGTATAGTCTGAAAATACCTCTAATCAAAATTATTTACTTGAGAAAAGTATTCAGAATAGTTCCTAAAAATTAAGAGTATATTTCTGGTATAAAAGGATAAATAATCTGTATATGAGTATTAATCCAATATTCTTAAAACTTCAGTATTTTACTTAAAAGTACTTTTTGTCATTAAAATTATAGCAAAGGTAGAATGCACTTGTTTAATATACTCTCATGATTCTTTTGCAGATTGTTCATTTAGAAGAAAGCAACACTAATGATTCAAACAGCTTCCTGAATTTTAATTTTGTGTTGTCTCACAGAAAGCCTTATCATAAATTCCATAATTCTAATTAATTTACCAAGATAATGTAATTACATTTGGTTTTGTAAGGTATACAGCAGTAATCTCCTATTTTGGTGTCAGTTTTTCAATAAAGTTTTGATTATGGGCAAA";
        
        StringBuilder builder = new StringBuilder();


        for( int i = 0; i < test.length(); i ++ ){

            char x = test.charAt(i);

            if(x == 'A' ) builder.append("U");
            
            else if (x == 'T') builder.append("A");
            
            else if (x == 'G') builder.append("C");
            
            else if (x == 'C') builder.append("G");
        }
        
        //test = test.Replace(".","*");
        
        
        System.out.println(builder);
        
    }
   


    
}
